{% set name = "geoschem-gcpy" %}
{% set version = "1.7.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 2d34d09e6e759cb19bd203d2e5af905c310efd227426169ce534d1cbd4debe50

build:
  number: 3
  skip: true  # [win or py<36]
  script_env:
    - MPLBACKEND=agg
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - numpy
    - cartopy
    - setuptools
    # Pin to ESMF 8.8.1 and xesmf 0.8.8 to avoid import errors
    - esmf =8.8.1
    - esmpy =8.8.1
    - xesmf =0.8.8 
  run:
    - cartopy
    - cf_xarray
    - dask
    # Pin to ESMF 8.8.1 to avoid import errors
    - esmf =8.8.1
    - esmpy =8.8.1
    - gridspec
    - joblib
    - matplotlib-base
    - netcdf4
    - netcdf-fortran
    - {{ pin_compatible('numpy') }}
    - pandas
    - pip
    - pylint
    - pypdf
    - pyproj
    - python
    - requests
    - scipy
    - sparselt
    - tabulate
    - tk
    - xarray
    # Pin to xesmf 0.8.8 to avoid import errors
    - xesmf =0.8.8 

test:
  imports:
    - gcpy
  requires:
    - esmf =8.8.1
    - esmpy =8.8.1
    - xesmf =0.8.8
  
about:
  home: https://github.com/geoschem/gcpy
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Python toolkit for working with GEOS-Chem output and input
  doc_url: https://gcpy.readthedocs.io/en/latest/
  dev_url: https://github.com/geoschem/gcpy

extra:
  recipe-maintainers:
    - yantosca
    - lizziel
    - msulprizio
