{% set name = "geoschem-gcpy" %}
{% set version = "1.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 2d34d09e6e759cb19bd203d2e5af905c310efd227426169ce534d1cbd4debe50

build:
  number: 6
  skip: true  # [win or py>=3.14]
  script_env:
    - MPLBACKEND=agg
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - numpy =2.1.3        # known-good version
    - cartopy =0.24.0     # known-good version
    - esmf =8.8.1
    - esmpy =8.8.1        # known-good version
    - xesmf =0.8.8        # known-good version
    - pip
    - setuptools

  run:
    - python
    - cartopy
    - cf_xarray
    - dask
    - esmf =8.8.1         # known-good version
    - esmpy =8.8.1        # known-good version
    - gridspec
    - joblib
    - matplotlib-base
    - netcdf4
    - netcdf-fortran
    - {{ pin_compatible('numpy') }}  # => >=2.1.3,<2.2.0 (keeps you on 2.1.x)
    - pandas
    - pip
    - pylint
    - pypdf
    - pyproj
    - requests
    - scipy
    - sparselt
    - tabulate
    - tk
    - xarray
    - xesmf =0.8.8        # known-good version

test:
  imports:
    - gcpy
  requires:
    - esmf =8.8.1
    - esmpy =8.8.1
    - xesmf =0.8.8

about:
  home: https://github.com/geoschem/gcpy
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Python toolkit for working with GEOS-Chem output and input
  doc_url: https://gcpy.readthedocs.io/en/latest/
  dev_url: https://github.com/geoschem/gcpy

extra:
  recipe-maintainers:
    - yantosca
    - lizziel
    - msulprizio
