{% set name = "geoschem-gcpy" %}
{% set version = "1.6.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 67240a50862e00295f939648aa85d8605b9b80cd20849c3325367f9597bcdf7d

build:
  number: 2
  skip: true  # [win or py<36]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - numpy >=1.26.4
    - cartopy >=0.23.0
  run:
    - cartopy >=0.23.0
    - dask >==2024.5.2
    - esmf >=8.6.1
    - esmpy >=8.6.1
    - gridspec==0.1.0
    - h5py >=2.9.0
    - h5netcdf
    - joblib >=1.4.2
    - matplotlib >=3.8.4
    - matplotlib-base >=3.
    - netcdf4 >=1.6.5
    - {{ pin_compatible('numpy') }}
    - pandas >=2.2.2
    - pypdf >=4.2.0
    - python
    - scipy >=1.13.1
    - sparselt >=0.1.3
    - sphinx
    - sphinx_rtd_theme
    - sphinx-autoapi
    - tabulate >=0.9.0
    - tk >=8.6.13
    - xarray >=2024.5.0
    - xesmf >=0.8.5

test:
  imports:
    - gcpy

about:
  home: https://github.com/geoschem/gcpy
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Python toolkit for working with GEOS-Chem output and input
  doc_url: https://gcpy.readthedocs.io/en/latest/
  dev_url: https://github.com/geoschem/gcpy

extra:
  recipe-maintainers:
    - yantosca
    - lizziel
    - msulprizio
